development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: wombatlinks
  password: qwertypoiuy
  database: wombatlinks_development
  schema_search_path: public
  encoding: utf8
  template: template1

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: wombatlinks
  password: qwertypoiuy
  database: wombatlinks_test
  schema_search_path: public
  encoding: utf8
  template: template1

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: wombatlinks
  password: qwertypoiuy
  database: wombatlinks
  schema_search_path: public
  encoding: utf8
  template: template1

