development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: linkme_ruby
  password: qwertpoiuy
  database: linkme_development
  schema_search_path: public
  encoding: utf8
  template: template1

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: linkme_ruby
  password: qwertpoiuy
  database: linkme_test
  schema_search_path: public
  encoding: utf8
  template: template1

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: linkme_ruby
  password: qwertpoiuy
  database: linkme
  schema_search_path: public
  encoding: utf8
  template: template1

