send_tweets_every_30_minutes:
 cron: "*/30 * * * *"
 class: TweetJob
 args:
 queue: TweetJob
 description: "Send tweets every 30 minutes"
 
delete_old_links_every_2_months:
 cron: "*/2 * * * *"
 class: DeleteOldLinksJob
 args:
 queue: DeleteJob
 description: "Delete old links every 2 months"
 
#minutes, hour, day of month, month, day of week
