send_tweets_every_30_minutes:
  cron: "/30 * * * *"
  class: TweetJob
  args:
  queue: TweetJob
  description: "Send tweets every 30 minutes"

delete_old_links_every_months:
  cron: "* * 20 * *"
  class: DeleteOldLinksJob
  args:
  queue: DeleteJob
  description: "Delete old links every 24 hours"

resend emails_every_15_minutes:
  cron: "0,15,30,45 * * * *"
  class: ReTryM/ailJob
  args:
  queue: MailJob
  description: "Resend email every 5 minutes"

recount_stats_every_4_hours:
  cron: "* /4 * * *"
  class: RecountStatsJob
  args:
  queue: RecountStatsJob
  description: "Recount stats every 4 hours"

monitor_every_hour:
  cron: "* /1 * * *"
  class: MonitorJob
  args:
  queue: MonitorJob
  description: "Run sites monitor"

delete_old_monitor_data_every_month:
  cron: "* * 10 * *"
  class: DeleteOldMonitorDataJob
  args:
  queue: DeleteOldMonitorDataJob
  description: "Delete old monitor data"

send statisctics_every_sunday_at_3_15:
  cron: "15 3 * * Sun"
  class: StatisticsMailJob
  args:
  queue: MailJob
  description: "Send statistics every Sunday"

#minutes, hour, day of month, month, day of week  /every
