bitly:
  login: "landria"
  api_key: "R_de421b9f20e1012c66b13504051ce7c8"
spam:
  max_spam_links_count: 4
deafult_link_mailer: "linker@wombatlinks.com"
anonymous_links_live_period: 3
resque:
  admin:
    user: admin
    pass: '123456'

registration:
  prepaid_period: 2 #months