bitly:
  login: "landria"
  api_key: "R_de421b9f20e1012c66b13504051ce7c8"
spam:
  max_spam_links_count: 4
deafult_link_mailer: "info@wombatlinks.com"
resque:
  admin:
    user: wombat_resque_admin
    pass: 'c66b1350'

registration:
  prepaid_period: 2 #months

twitter:
  consumer_key: "HnfrHschyZTuaKvpfNbIjw"
  consumer_secret: "6CazHvMEEOGn2ENLqxN67yJVVsay3LIichxYt0LI"
  oauth_token: "252527222-KqiZ9ngs6l2B5Yphe6uMsTJzxeawtSbwT913VE7d"
  oauth_token_secret: "H2sHEXQws9PAE9y0QL6ByEwgwafntAf9Wf8HOMcv0"