spam:
  max_spam_links_count: 4
deafult_link_mailer: "info@wombatlinks.com"
registration:
  prepaid_period: 2 #months

twitter:
  consumer_key: ""
  consumer_secret: ""
  oauth_token: ""
  oauth_token_secret: ""